#!/bin/bash

# TCP_and_UDP
echo "Active Internet connections (only servers)"
sudo netstat -tulnp | grep -E '^(tcp|udp)' || echo "Aucune connexion Internet active trouvée."

echo
echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxnp | grep LISTEN || echo "Aucune socket UNIX en écoute trouvée."
